[sources.kafka]
type = "kafka"
bootstrap_servers = "kafka:19092"
group_id = "vector-group"
topics = ["dns.logs"]

[transforms.parse_json]
type = "remap"
inputs = ["kafka"]
source = '''
structured = parse_json!(.message)

.time = structured.time
.level = structured.level
.domain = structured.domain
.client_ip = structured.client_ip
.qtype = structured.qtype
.resolver = structured.resolver

[sinks.loki]
type = "loki"
inputs = ["parse_json"]
endpoint = "http://loki:3100"
encoding.codec = "json"
labels.job = "dns-resolver"
labels.domain = "{{ .domain }}"
labels.client_ip = "{{ .client_ip }}"
labels.qtype = "{{ .qtype }}"
labels.resolver = "{{ .resolver }}"
healthcheck.enabled = true

[sinks.loki.request]
retry_attempts = 10
retry_backoff_secs = 2
