port: 5354
upstream_addrs:
  - 8.8.8.8:53
  - 1.1.1.1:53
domain_resolvers:
  - domain: google.com
    resolvers:
      - 1.1.1.1:53
      - 4.2.2.2:53
domain_redirect:
  - domain: youtube.com
    ip: 1.1.1.1:443
    redirect_domain: google.com
blocked_domains:
  - spotify.com
kafka:
  servers: localhost:9092
  client_id: dns-server
  log_topic: dns.logs