version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "dns.logs:1:1"
    depends_on:
      - zookeeper

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./confs/loki-config.yaml:/etc/loki/local-config.yaml


  clickhouse:
    image: yandex/clickhouse-server:21.8.10.19
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  vector:
    image: timberio/vector:0.25.1-alpine
    container_name: vector
    volumes:
      - ./confs/vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - kafka
      - loki
      - clickhouse

  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./confs/grafana/:/etc/grafana/provisioning/
    depends_on:
      - loki
      - clickhouse

volumes:
  clickhouse-data:
  grafana-data:
